name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Install dependencies"
      run: |
        sudo apt-get install python3 python3-sphinx
    - uses: ammaraskar/sphinx-problem-matcher@master
    - name: "Build docs"
      run: |
        cd docs
        make html
