name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-problem-matcher@master
    - name: "Build docs"
      run: |
        sudo apt-get install python
        pip install sphinx
        cd docs
        make html
